[project]
name = "nixmcp"
version = "0.1.0"
description = "Model Context Protocol server for NixOS resources"
readme = "README.md"
authors = [
    {name = "James Brink", email = "user@example.com"},
]
requires-python = ">=3.9"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]
dependencies = [
    "mcp>=1.4.0",
    "fastapi>=0.95.0",
    "uvicorn>=0.21.0",
]