name: Windows Tests

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  windows-tests:
    runs-on: windows-latest
    strategy:
      fail-fast: false
    
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install build pytest pytest-cov pytest-asyncio
          python -m pip install -e ".[dev,win]"
        shell: bash
      
      - name: Run unit tests
        run: |
          $env:MCP_NIXOS_CACHE_DIR = Join-Path $env:RUNNER_TEMP "mcp_nixos_test_cache_win"
          python -m pytest tests/ -v --unit
        shell: pwsh
      
      - name: Run integration tests
        run: |
          $env:MCP_NIXOS_CACHE_DIR = Join-Path $env:RUNNER_TEMP "mcp_nixos_test_cache_win"
          python -m pytest tests/ -v --integration
        shell: pwsh
      
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: windows-test-results
          path: |
            mcp_nixos_test_cache_win/
            htmlcov/
            coverage.xml
          retention-days: 5
          if-no-files-found: warn